image: continuumio/miniconda3:4.1.11

before_script:
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install snakemake==3.12.0
stages:
    - rulegraph
    
# DAG
rulegraph:
  stage: rulegraph
  script: 
    - snakemake --rulegraph --use-conda