---
title: "Hydra report"
author: "Mattias  de Hollander (m.dehollander@nioo.knaw.nl)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    highlight: tango
    number_sections: no
    theme: default
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---


# `r snakemake@config$project`

## Info
Forward primer: `r snakemake@config$forward_primer`

Reverse primer: `r snakemake@config$reverse_primer`

Silva database: `r basename(snakemake@config$silva_arb)`

### Input files

```{r kable, message=FALSE, warning=FALSE}
library(knitr)
kable(snakemake@config$data)
```

## Summary
Reads have been merged with `r snakemake@params[["mergemethod"]]`

## Plot
```{r cars, message=FALSE, warning=FALSE}
library(plotly)
readstat = read.csv(snakemake@input$readstat)
p <- ggplot(readstat, aes(y=readstat$avg_len, x = seq(1, length(readstat$avg_len)))) + geom_point()

ggplotly(p)
```

## Files
<a download="`r basename(snakemake@input$biom)`" href="`r base64enc::dataURI(file = snakemake@input$biom, mime = 'text/csv', encoding = 'base64')`">BIOM file</a>
